// dummyData.js
export const dummyData = [
    {
      id: 1,
      traceId: 'T001',
      transactionId: 'TXN001',
      paymentProviderId: 'PP001',
      fkpaymentRefundId: 'RF001',
      paymentType: 'Credit Card',
      collectionAmount: '$100',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 10:00:00',
      insertedDatetime: '2024-09-10 09:55:00',
      updatedDatetime: '2024-09-10 09:59:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '5s',
      paymentProvider: 'Provider A',
      providerResponse: 'Approved'
    },
    {
      id: 2,
      traceId: 'T002',
      transactionId: 'TXN002',
      paymentProviderId: 'PP002',
      fkpaymentRefundId: 'RF002',
      paymentType: 'Debit Card',
      collectionAmount: '$200',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '01',
      status: 'Failed',
      message: 'Transaction failed',
      httpResponseCode: '400',
      paymentProviderTimestamp: '2024-09-10 11:00:00',
      insertedDatetime: '2024-09-10 10:55:00',
      updatedDatetime: '2024-09-10 10:59:00',
      beneStatus: 'Inactive',
      paymentProviderStatusReasonCode: 'Reason 02',
      paymentProviderPaymentStatus: 'Failed',
      paymentProviderPaymentMessage: 'Payment rejected',
      paymentProviderStatusResponseTime: '7s',
      paymentProvider: 'Provider B',
      providerResponse: 'Rejected'
    },
    {
      id: 3,
      traceId: 'T003',
      transactionId: 'TXN003',
      paymentProviderId: 'PP003',
      fkpaymentRefundId: 'RF003',
      paymentType: 'PayPal',
      collectionAmount: '$150',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 11:30:00',
      insertedDatetime: '2024-09-10 11:15:00',
      updatedDatetime: '2024-09-10 11:25:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '6s',
      paymentProvider: 'Provider C',
      providerResponse: 'Approved'
    },
    {
      id: 4,
      traceId: 'T004',
      transactionId: 'TXN004',
      paymentProviderId: 'PP004',
      fkpaymentRefundId: 'RF004',
      paymentType: 'Net Banking',
      collectionAmount: '$300',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '01',
      status: 'Pending',
      message: 'Transaction pending',
      httpResponseCode: '202',
      paymentProviderTimestamp: '2024-09-10 12:00:00',
      insertedDatetime: '2024-09-10 11:45:00',
      updatedDatetime: '2024-09-10 11:55:00',
      beneStatus: 'Pending',
      paymentProviderStatusReasonCode: 'Reason 02',
      paymentProviderPaymentStatus: 'Pending',
      paymentProviderPaymentMessage: 'Awaiting approval',
      paymentProviderStatusResponseTime: '8s',
      paymentProvider: 'Provider D',
      providerResponse: 'Pending'
    },
    // Additional 15 rows for the table
    {
      id: 5,
      traceId: 'T005',
      transactionId: 'TXN005',
      paymentProviderId: 'PP005',
      fkpaymentRefundId: 'RF005',
      paymentType: 'UPI',
      collectionAmount: '$250',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 12:15:00',
      insertedDatetime: '2024-09-10 12:00:00',
      updatedDatetime: '2024-09-10 12:10:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 03',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '3s',
      paymentProvider: 'Provider E',
      providerResponse: 'Approved'
    },
    {
      id: 6,
      traceId: 'T006',
      transactionId: 'TXN006',
      paymentProviderId: 'PP006',
      fkpaymentRefundId: 'RF006',
      paymentType: 'Google Pay',
      collectionAmount: '$180',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 12:30:00',
      insertedDatetime: '2024-09-10 12:20:00',
      updatedDatetime: '2024-09-10 12:25:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '4s',
      paymentProvider: 'Provider F',
      providerResponse: 'Approved'
    },
    {
      id: 7,
      traceId: 'T007',
      transactionId: 'TXN007',
      paymentProviderId: 'PP007',
      fkpaymentRefundId: 'RF007',
      paymentType: 'Apple Pay',
      collectionAmount: '$500',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '01',
      status: 'Failed',
      message: 'Transaction failed',
      httpResponseCode: '400',
      paymentProviderTimestamp: '2024-09-10 12:45:00',
      insertedDatetime: '2024-09-10 12:35:00',
      updatedDatetime: '2024-09-10 12:40:00',
      beneStatus: 'Inactive',
      paymentProviderStatusReasonCode: 'Reason 02',
      paymentProviderPaymentStatus: 'Failed',
      paymentProviderPaymentMessage: 'Payment rejected',
      paymentProviderStatusResponseTime: '6s',
      paymentProvider: 'Provider G',
      providerResponse: 'Rejected'
    },
    {
      id: 8,
      traceId: 'T008',
      transactionId: 'TXN008',
      paymentProviderId: 'PP008',
      fkpaymentRefundId: 'RF008',
      paymentType: 'Net Banking',
      collectionAmount: '$700',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 13:00:00',
      insertedDatetime: '2024-09-10 12:50:00',
      updatedDatetime: '2024-09-10 12:55:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 03',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '3s',
      paymentProvider: 'Provider H',
      providerResponse: 'Approved'
    },
    {
      id: 9,
      traceId: 'T009',
      transactionId: 'TXN009',
      paymentProviderId: 'PP009',
      fkpaymentRefundId: 'RF009',
      paymentType: 'Credit Card',
      collectionAmount: '$220',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 13:15:00',
      insertedDatetime: '2024-09-10 13:00:00',
      updatedDatetime: '2024-09-10 13:05:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '5s',
      paymentProvider: 'Provider I',
      providerResponse: 'Approved'
    },
    {
      id: 10,
      traceId: 'T010',
      transactionId: 'TXN010',
      paymentProviderId: 'PP010',
      fkpaymentRefundId: 'RF010',
      paymentType: 'Debit Card',
      collectionAmount: '$450',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 13:30:00',
      insertedDatetime: '2024-09-10 13:15:00',
      updatedDatetime: '2024-09-10 13:25:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 02',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '4s',
      paymentProvider: 'Provider J',
      providerResponse: 'Approved'
    },
    {
      id: 11,
      traceId: 'T011',
      transactionId: 'TXN011',
      paymentProviderId: 'PP011',
      fkpaymentRefundId: 'RF011',
      paymentType: 'Google Pay',
      collectionAmount: '$300',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '01',
      status: 'Failed',
      message: 'Transaction failed',
      httpResponseCode: '400',
      paymentProviderTimestamp: '2024-09-10 13:45:00',
      insertedDatetime: '2024-09-10 13:30:00',
      updatedDatetime: '2024-09-10 13:40:00',
      beneStatus: 'Inactive',
      paymentProviderStatusReasonCode: 'Reason 03',
      paymentProviderPaymentStatus: 'Failed',
      paymentProviderPaymentMessage: 'Payment rejected',
      paymentProviderStatusResponseTime: '6s',
      paymentProvider: 'Provider K',
      providerResponse: 'Rejected'
    },
    {
      id: 12,
      traceId: 'T012',
      transactionId: 'TXN012',
      paymentProviderId: 'PP012',
      fkpaymentRefundId: 'RF012',
      paymentType: 'UPI',
      collectionAmount: '$120',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 14:00:00',
      insertedDatetime: '2024-09-10 13:50:00',
      updatedDatetime: '2024-09-10 13:55:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '3s',
      paymentProvider: 'Provider L',
      providerResponse: 'Approved'
    },
    {
      id: 13,
      traceId: 'T013',
      transactionId: 'TXN013',
      paymentProviderId: 'PP013',
      fkpaymentRefundId: 'RF013',
      paymentType: 'Net Banking',
      collectionAmount: '$600',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '01',
      status: 'Failed',
      message: 'Transaction failed',
      httpResponseCode: '500',
      paymentProviderTimestamp: '2024-09-10 14:15:00',
      insertedDatetime: '2024-09-10 14:00:00',
      updatedDatetime: '2024-09-10 14:05:00',
      beneStatus: 'Inactive',
      paymentProviderStatusReasonCode: 'Reason 02',
      paymentProviderPaymentStatus: 'Failed',
      paymentProviderPaymentMessage: 'Payment rejected',
      paymentProviderStatusResponseTime: '5s',
      paymentProvider: 'Provider M',
      providerResponse: 'Rejected'
    },
    {
      id: 14,
      traceId: 'T014',
      transactionId: 'TXN014',
      paymentProviderId: 'PP014',
      fkpaymentRefundId: 'RF014',
      paymentType: 'Apple Pay',
      collectionAmount: '$400',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 14:30:00',
      insertedDatetime: '2024-09-10 14:20:00',
      updatedDatetime: '2024-09-10 14:25:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 01',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '4s',
      paymentProvider: 'Provider N',
      providerResponse: 'Approved'
    },
    {
      id: 15,
      traceId: 'T015',
      transactionId: 'TXN015',
      paymentProviderId: 'PP015',
      fkpaymentRefundId: 'RF015',
      paymentType: 'Credit Card',
      collectionAmount: '$550',
      redirectUrl: 'http://example.com',
      statusUrl: 'http://example.com/status',
      paymentProviderReasonCode: '00',
      status: 'Completed',
      message: 'Transaction successful',
      httpResponseCode: '200',
      paymentProviderTimestamp: '2024-09-10 14:45:00',
      insertedDatetime: '2024-09-10 14:30:00',
      updatedDatetime: '2024-09-10 14:40:00',
      beneStatus: 'Active',
      paymentProviderStatusReasonCode: 'Reason 03',
      paymentProviderPaymentStatus: 'Success',
      paymentProviderPaymentMessage: 'Payment processed',
      paymentProviderStatusResponseTime: '3s',
      paymentProvider: 'Provider O',
      providerResponse: 'Approved'
    },
    {
        id: 1,
        traceId: 'T001',
        transactionId: 'TXN001',
        paymentProviderId: 'PP001',
        fkpaymentRefundId: 'RF001',
        paymentType: 'Credit Card',
        collectionAmount: '$100',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 10:00:00',
        insertedDatetime: '2024-09-10 09:55:00',
        updatedDatetime: '2024-09-10 09:59:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '5s',
        paymentProvider: 'Provider A',
        providerResponse: 'Approved'
      },
      {
        id: 2,
        traceId: 'T002',
        transactionId: 'TXN002',
        paymentProviderId: 'PP002',
        fkpaymentRefundId: 'RF002',
        paymentType: 'Debit Card',
        collectionAmount: '$200',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '01',
        status: 'Failed',
        message: 'Transaction failed',
        httpResponseCode: '400',
        paymentProviderTimestamp: '2024-09-10 11:00:00',
        insertedDatetime: '2024-09-10 10:55:00',
        updatedDatetime: '2024-09-10 10:59:00',
        beneStatus: 'Inactive',
        paymentProviderStatusReasonCode: 'Reason 02',
        paymentProviderPaymentStatus: 'Failed',
        paymentProviderPaymentMessage: 'Payment rejected',
        paymentProviderStatusResponseTime: '7s',
        paymentProvider: 'Provider B',
        providerResponse: 'Rejected'
      },
      {
        id: 3,
        traceId: 'T003',
        transactionId: 'TXN003',
        paymentProviderId: 'PP003',
        fkpaymentRefundId: 'RF003',
        paymentType: 'PayPal',
        collectionAmount: '$150',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 11:30:00',
        insertedDatetime: '2024-09-10 11:15:00',
        updatedDatetime: '2024-09-10 11:25:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '6s',
        paymentProvider: 'Provider C',
        providerResponse: 'Approved'
      },
      {
        id: 4,
        traceId: 'T004',
        transactionId: 'TXN004',
        paymentProviderId: 'PP004',
        fkpaymentRefundId: 'RF004',
        paymentType: 'Net Banking',
        collectionAmount: '$300',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '01',
        status: 'Pending',
        message: 'Transaction pending',
        httpResponseCode: '202',
        paymentProviderTimestamp: '2024-09-10 12:00:00',
        insertedDatetime: '2024-09-10 11:45:00',
        updatedDatetime: '2024-09-10 11:55:00',
        beneStatus: 'Pending',
        paymentProviderStatusReasonCode: 'Reason 02',
        paymentProviderPaymentStatus: 'Pending',
        paymentProviderPaymentMessage: 'Awaiting approval',
        paymentProviderStatusResponseTime: '8s',
        paymentProvider: 'Provider D',
        providerResponse: 'Pending'
      },
      // Additional 15 rows for the table
      {
        id: 5,
        traceId: 'T005',
        transactionId: 'TXN005',
        paymentProviderId: 'PP005',
        fkpaymentRefundId: 'RF005',
        paymentType: 'UPI',
        collectionAmount: '$250',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 12:15:00',
        insertedDatetime: '2024-09-10 12:00:00',
        updatedDatetime: '2024-09-10 12:10:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 03',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '3s',
        paymentProvider: 'Provider E',
        providerResponse: 'Approved'
      },
      {
        id: 6,
        traceId: 'T006',
        transactionId: 'TXN006',
        paymentProviderId: 'PP006',
        fkpaymentRefundId: 'RF006',
        paymentType: 'Google Pay',
        collectionAmount: '$180',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 12:30:00',
        insertedDatetime: '2024-09-10 12:20:00',
        updatedDatetime: '2024-09-10 12:25:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '4s',
        paymentProvider: 'Provider F',
        providerResponse: 'Approved'
      },
      {
        id: 7,
        traceId: 'T007',
        transactionId: 'TXN007',
        paymentProviderId: 'PP007',
        fkpaymentRefundId: 'RF007',
        paymentType: 'Apple Pay',
        collectionAmount: '$500',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '01',
        status: 'Failed',
        message: 'Transaction failed',
        httpResponseCode: '400',
        paymentProviderTimestamp: '2024-09-10 12:45:00',
        insertedDatetime: '2024-09-10 12:35:00',
        updatedDatetime: '2024-09-10 12:40:00',
        beneStatus: 'Inactive',
        paymentProviderStatusReasonCode: 'Reason 02',
        paymentProviderPaymentStatus: 'Failed',
        paymentProviderPaymentMessage: 'Payment rejected',
        paymentProviderStatusResponseTime: '6s',
        paymentProvider: 'Provider G',
        providerResponse: 'Rejected'
      },
      {
        id: 8,
        traceId: 'T008',
        transactionId: 'TXN008',
        paymentProviderId: 'PP008',
        fkpaymentRefundId: 'RF008',
        paymentType: 'Net Banking',
        collectionAmount: '$700',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 13:00:00',
        insertedDatetime: '2024-09-10 12:50:00',
        updatedDatetime: '2024-09-10 12:55:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 03',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '3s',
        paymentProvider: 'Provider H',
        providerResponse: 'Approved'
      },
      {
        id: 9,
        traceId: 'T009',
        transactionId: 'TXN009',
        paymentProviderId: 'PP009',
        fkpaymentRefundId: 'RF009',
        paymentType: 'Credit Card',
        collectionAmount: '$220',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 13:15:00',
        insertedDatetime: '2024-09-10 13:00:00',
        updatedDatetime: '2024-09-10 13:05:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '5s',
        paymentProvider: 'Provider I',
        providerResponse: 'Approved'
      },
      {
        id: 10,
        traceId: 'T010',
        transactionId: 'TXN010',
        paymentProviderId: 'PP010',
        fkpaymentRefundId: 'RF010',
        paymentType: 'Debit Card',
        collectionAmount: '$450',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 13:30:00',
        insertedDatetime: '2024-09-10 13:15:00',
        updatedDatetime: '2024-09-10 13:25:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 02',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '4s',
        paymentProvider: 'Provider J',
        providerResponse: 'Approved'
      },
      {
        id: 11,
        traceId: 'T011',
        transactionId: 'TXN011',
        paymentProviderId: 'PP011',
        fkpaymentRefundId: 'RF011',
        paymentType: 'Google Pay',
        collectionAmount: '$300',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '01',
        status: 'Failed',
        message: 'Transaction failed',
        httpResponseCode: '400',
        paymentProviderTimestamp: '2024-09-10 13:45:00',
        insertedDatetime: '2024-09-10 13:30:00',
        updatedDatetime: '2024-09-10 13:40:00',
        beneStatus: 'Inactive',
        paymentProviderStatusReasonCode: 'Reason 03',
        paymentProviderPaymentStatus: 'Failed',
        paymentProviderPaymentMessage: 'Payment rejected',
        paymentProviderStatusResponseTime: '6s',
        paymentProvider: 'Provider K',
        providerResponse: 'Rejected'
      },
      {
        id: 12,
        traceId: 'T012',
        transactionId: 'TXN012',
        paymentProviderId: 'PP012',
        fkpaymentRefundId: 'RF012',
        paymentType: 'UPI',
        collectionAmount: '$120',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 14:00:00',
        insertedDatetime: '2024-09-10 13:50:00',
        updatedDatetime: '2024-09-10 13:55:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '3s',
        paymentProvider: 'Provider L',
        providerResponse: 'Approved'
      },
      {
        id: 13,
        traceId: 'T013',
        transactionId: 'TXN013',
        paymentProviderId: 'PP013',
        fkpaymentRefundId: 'RF013',
        paymentType: 'Net Banking',
        collectionAmount: '$600',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '01',
        status: 'Failed',
        message: 'Transaction failed',
        httpResponseCode: '500',
        paymentProviderTimestamp: '2024-09-10 14:15:00',
        insertedDatetime: '2024-09-10 14:00:00',
        updatedDatetime: '2024-09-10 14:05:00',
        beneStatus: 'Inactive',
        paymentProviderStatusReasonCode: 'Reason 02',
        paymentProviderPaymentStatus: 'Failed',
        paymentProviderPaymentMessage: 'Payment rejected',
        paymentProviderStatusResponseTime: '5s',
        paymentProvider: 'Provider M',
        providerResponse: 'Rejected'
      },
      {
        id: 14,
        traceId: 'T014',
        transactionId: 'TXN014',
        paymentProviderId: 'PP014',
        fkpaymentRefundId: 'RF014',
        paymentType: 'Apple Pay',
        collectionAmount: '$400',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 14:30:00',
        insertedDatetime: '2024-09-10 14:20:00',
        updatedDatetime: '2024-09-10 14:25:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 01',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '4s',
        paymentProvider: 'Provider N',
        providerResponse: 'Approved'
      },
      {
        id: 15,
        traceId: 'T015',
        transactionId: 'TXN015',
        paymentProviderId: 'PP015',
        fkpaymentRefundId: 'RF015',
        paymentType: 'Credit Card',
        collectionAmount: '$550',
        redirectUrl: 'http://example.com',
        statusUrl: 'http://example.com/status',
        paymentProviderReasonCode: '00',
        status: 'Completed',
        message: 'Transaction successful',
        httpResponseCode: '200',
        paymentProviderTimestamp: '2024-09-10 14:45:00',
        insertedDatetime: '2024-09-10 14:30:00',
        updatedDatetime: '2024-09-10 14:40:00',
        beneStatus: 'Active',
        paymentProviderStatusReasonCode: 'Reason 03',
        paymentProviderPaymentStatus: 'Success',
        paymentProviderPaymentMessage: 'Payment processed',
        paymentProviderStatusResponseTime: '3s',
        paymentProvider: 'Provider O',
        providerResponse: 'Approved'
      }
  ];
  